# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://wowchemy.com/docs/guide/language/

# Default language
ms: 
  languageCode: ms
  languageName: Bahasa Melayu
  contentDir: content/ms

ms-arab:
  languageCode: ms-Arab
  languageName: بهاس ملايو
  languagedirection: rtl
  contentDir: content/ms-Arab
  title: ‮روجوعن نيسکالا
  params:
    description: ڤريحلن سساوڠ دالم توليسن جاوي بربهاس ملايو
  menu:
    main:
      - name: انته
        url: '#about'
        weight: 1

en:
  languageCode: en
  languageName: English
  contentDir: content/en
  title: Niskala's Reference
  params:
    description: Site description in English...
  menu:
    main:
      - name: IDK
        url: '#about'
        weight: 2
