# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://wowchemy.com/docs/guide/language/

# Default language
ms:
  languageCode: ms
  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  contentDir: content/ms

# Uncomment the lines below to configure your website in a second language.
ms-arab:
  languageCode: ms-Arab
  contentDir: content/ms-Arab
  title: تاجوق دالم توليسن جاوي...
  params:
    description: ڤريحلن سساوڠ دالم توليسن جاوي بربهاس ملايو
  menu:
    main:
      - name: انته
        url: '#about'
        weight: 1

en:
  languageCode: en
  contentDir: content/en
  title: English website title...
  params:
    description: Site description in English...
  menu:
    main:
      - name: IDK
        url: '#about'
        weight: 2